[{
    "Type": "tablet",
    "Device": "Apple iPad 1 & 2",
    "Operating System": "iOS",
    "Physical Size": "9.7",
    "Physical SizeCM": "25.0",
    "WidthPX": "768",
    "HeightPX": "1024",
    "Device-widthPX": "768",
    "Px Per Inch": "132",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "3 : 4",
    "Popularity%": "25.0%"
}, {
    "Type": "tablet",
    "Device": "Apple IPad 3 & 4",
    "Operating System": "iOS",
    "Physical Size": "9.7",
    "Physical SizeCM": "25.0",
    "WidthPX": "1536",
    "HeightPX": "2048",
    "Device-widthPX": "768",
    "Px Per Inch": "264",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 4",
    "Popularity%": "24.9%"
}, {
    "Type": "tablet",
    "Device": "Google Nexus 10 by Samsung",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "1600",
    "HeightPX": "2560",
    "Device-widthPX": "800",
    "Px Per Inch": "300",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "10.5%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 13-inch (Mid 2009 - Mid 2012)",
    "Operating System": "OS X",
    "Physical Size": "13.3",
    "Physical SizeCM": "34.0",
    "WidthPX": "1280",
    "HeightPX": "800",
    "Device-widthPX": "1280",
    "Px Per Inch": "113",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "10.2%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 15-inch (Hi-Res screen)",
    "Operating System": "OS X",
    "Physical Size": "15.4",
    "Physical SizeCM": "39.0",
    "WidthPX": "1680",
    "HeightPX": "1050",
    "Device-widthPX": "1680",
    "Px Per Inch": "128",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "9.9%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 15-inch (Early 2006 - Mid 2012)",
    "Operating System": "OS X",
    "Physical Size": "15.4",
    "Physical SizeCM": "39.0",
    "WidthPX": "1440",
    "HeightPX": "900",
    "Device-widthPX": "1440",
    "Px Per Inch": "110",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "9.9%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 17-inch (Mid/Late 2007 - Late 2011)",
    "Operating System": "OS X",
    "Physical Size": "17.3",
    "Physical SizeCM": "44.0",
    "WidthPX": "1920",
    "HeightPX": "1200",
    "Device-widthPX": "1920",
    "Px Per Inch": "131",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "9.7%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 13-inch (Retina display)",
    "Operating System": "OS X",
    "Physical Size": "13.3",
    "Physical SizeCM": "34.0",
    "WidthPX": "2560",
    "HeightPX": "1600",
    "Device-widthPX": "1280",
    "Px Per Inch": "227",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "9.7%"
}, {
    "Type": "monitor",
    "Device": "MacBook Pro 15-inch (Retina display)",
    "Operating System": "OS X",
    "Physical Size": "15.4",
    "Physical SizeCM": "39.0",
    "WidthPX": "2880",
    "HeightPX": "1800",
    "Device-widthPX": "1440",
    "Px Per Inch": "220",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "9.6%"
}, {
    "Type": "phone",
    "Device": "iPhone 4 (4, 4S)",
    "Operating System": "iOS",
    "Physical Size": "3.5",
    "Physical SizeCM": "8.9",
    "WidthPX": "640",
    "HeightPX": "960",
    "Device-widthPX": "320",
    "Px Per Inch": "326",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "2 : 3",
    "Popularity%": "8.8%"
}, {
    "Type": "phone",
    "Device": "Galaxy SIII",
    "Operating System": "Android",
    "Physical Size": "4.8",
    "Physical SizeCM": "12.0",
    "WidthPX": "720",
    "HeightPX": "1280",
    "Device-widthPX": "360",
    "Px Per Inch": "306",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "8.8%"
}, {
    "Type": "phone",
    "Device": "iPhone 5 (5c, 5s)",
    "Operating System": "iOS",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "640",
    "HeightPX": "1136",
    "Device-widthPX": "320",
    "Px Per Inch": "326",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "40 : 71",
    "Popularity%": "7.9%"
}, {
    "Type": "monitor",
    "Device": "iMac 27-inch (Late 2009 - Late 2012)",
    "Operating System": "OS X",
    "Physical Size": "27.0",
    "Physical SizeCM": "69.0",
    "WidthPX": "2560",
    "HeightPX": "1440",
    "Device-widthPX": "2560",
    "Px Per Inch": "109",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "6.7%"
}, {
    "Type": "monitor",
    "Device": "iMac 21.5-inch (Late 2009 - Late 2012)",
    "Operating System": "OS X",
    "Physical Size": "21.5",
    "Physical SizeCM": "55.0",
    "WidthPX": "1920",
    "HeightPX": "1080",
    "Device-widthPX": "1920",
    "Px Per Inch": "102",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "6.5%"
}, {
    "Type": "phone",
    "Device": "Galaxy SII",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "10.8",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "219",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "6.4%"
}, {
    "Type": "tablet",
    "Device": "Samsung Galaxy Tab",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "600",
    "HeightPX": "1024",
    "Device-widthPX": "600",
    "Px Per Inch": "171",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "75 : 128",
    "Popularity%": "6.1%"
}, {
    "Type": "phone",
    "Device": "Google Nexus 4 by LG",
    "Operating System": "Android",
    "Physical Size": "4.7",
    "Physical SizeCM": "12.0",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "384",
    "Px Per Inch": "320",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "6.1%"
}, {
    "Type": "phone",
    "Device": "Galaxy Nexus",
    "Operating System": "Android",
    "Physical Size": "4.6",
    "Physical SizeCM": "11.8",
    "WidthPX": "720",
    "HeightPX": "1280",
    "Device-widthPX": "360",
    "Px Per Inch": "316",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "6.1%"
}, {
    "Type": "tablet",
    "Device": "Samsung Galaxy Tab 2",
    "Operating System": "Android",
    "Physical Size": "7.7",
    "Physical SizeCM": "20.0",
    "WidthPX": "600",
    "HeightPX": "1024",
    "Device-widthPX": "600",
    "Px Per Inch": "170",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "75 : 128",
    "Popularity%": "5.3%"
}, {
    "Type": "phone",
    "Device": "Galaxy SIV",
    "Operating System": "Android",
    "Physical Size": "5.0",
    "Physical SizeCM": "12.7",
    "WidthPX": "1080",
    "HeightPX": "1920",
    "Device-widthPX": "360",
    "Px Per Inch": "441",
    "Px Density": "300%  XXHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "4.6%"
}, {
    "Type": "monitor",
    "Device": "MacBook Air 13-inch (Late 2010 - Mid 2012)",
    "Operating System": "OS X",
    "Physical Size": "13.3",
    "Physical SizeCM": "34.0",
    "WidthPX": "1440",
    "HeightPX": "900",
    "Device-widthPX": "1440",
    "Px Per Inch": "128",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "4.5%"
}, {
    "Type": "monitor",
    "Device": "MacBook Air 11-inch (Late 2010 - Mid 2012)",
    "Operating System": "OS X",
    "Physical Size": "11.6",
    "Physical SizeCM": "29.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "135",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "4.4%"
}, {
    "Type": "monitor",
    "Device": "LENOVO THINKPAD X230",
    "Operating System": "Windows",
    "Physical Size": "12.5",
    "Physical SizeCM": "32.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "125",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "4.3%"
}, {
    "Type": "monitor",
    "Device": "DELL Inspiron 14 series 36\"",
    "Operating System": "Windows",
    "Physical Size": "14.1",
    "Physical SizeCM": "36.0",
    "WidthPX": "1600",
    "HeightPX": "900",
    "Device-widthPX": "1600",
    "Px Per Inch": "130",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "4.3%"
}, {
    "Type": "tablet",
    "Device": "Samsung Galaxy Tab 10.1",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "25.7",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "533",
    "Px Per Inch": "149",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "4.2%"
}, {
    "Type": "tablet",
    "Device": "Samsung Galaxy Tab 2 10.1",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "800",
    "Px Per Inch": "149",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "4.0%"
}, {
    "Type": "phone",
    "Device": "Galaxy S Plus",
    "Operating System": "Android",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "233",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "3.7%"
}, {
    "Type": "phone",
    "Device": "Galaxy Note II",
    "Operating System": "Android",
    "Physical Size": "5.5",
    "Physical SizeCM": "14.1",
    "WidthPX": "720",
    "HeightPX": "1280",
    "Device-widthPX": "360",
    "Px Per Inch": "267",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "3.7%"
}, {
    "Type": "phone",
    "Device": "Galaxy S",
    "Operating System": "Android",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "233",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "3.6%"
}, {
    "Type": "tablet",
    "Device": "Asus Nexus 7 (2012)",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "603",
    "Px Per Inch": "216",
    "Px Density": "N/A  undefined",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "3.6%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 520",
    "Operating System": "Windows",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "233",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "3.0%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 925",
    "Operating System": "Windows",
    "Physical Size": "4.5",
    "Physical SizeCM": "11.0",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "384",
    "Px Per Inch": "332",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.9%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 1020",
    "Operating System": "Windows",
    "Physical Size": "4.5",
    "Physical SizeCM": "11.0",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "384",
    "Px Per Inch": "332",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.9%"
}, {
    "Type": "phone",
    "Device": "iPhone (Original - 3GS)",
    "Operating System": "iOS",
    "Physical Size": "3.5",
    "Physical SizeCM": "8.9",
    "WidthPX": "320",
    "HeightPX": "480",
    "Device-widthPX": "320",
    "Px Per Inch": "163",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "2 : 3",
    "Popularity%": "2.9%"
}, {
    "Type": "phone",
    "Device": "Galaxy Note",
    "Operating System": "Android",
    "Physical Size": "5.3",
    "Physical SizeCM": "13.5",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "400",
    "Px Per Inch": "285",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "2.9%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 920",
    "Operating System": "Windows",
    "Physical Size": "4.5",
    "Physical SizeCM": "11.0",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "384",
    "Px Per Inch": "332",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.7%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia (710, 800)",
    "Operating System": "Windows",
    "Physical Size": "3.7",
    "Physical SizeCM": "9.4",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "252",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.7%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 900",
    "Operating System": "Windows",
    "Physical Size": "4.3",
    "Physical SizeCM": "11.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "217",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.6%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 620",
    "Operating System": "Windows",
    "Physical Size": "3.8",
    "Physical SizeCM": "9.7",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "246",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.5%"
}, {
    "Type": "phone",
    "Device": "Nokia Lumia 720",
    "Operating System": "Windows",
    "Physical Size": "4.3",
    "Physical SizeCM": "10.9",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "217",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "2.4%"
}, {
    "Type": "tablet",
    "Device": "Apple iPad Mini",
    "Operating System": "iOS",
    "Physical Size": "7.9",
    "Physical SizeCM": "20.0",
    "WidthPX": "768",
    "HeightPX": "1024",
    "Device-widthPX": "768",
    "Px Per Inch": "163",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "3 : 4",
    "Popularity%": "2.4%"
}, {
    "Type": "tablet",
    "Device": "Amazon Kindle Fire HD 8.9\"",
    "Operating System": "Android",
    "Physical Size": "8.9",
    "Physical SizeCM": "23.0",
    "WidthPX": "1200",
    "HeightPX": "1920",
    "Device-widthPX": "800",
    "Px Per Inch": "254",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "2.0%"
}, {
    "Type": "tablet",
    "Device": "Amazon Kindle Fire HD 7\"",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "533",
    "Px Per Inch": "216",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "2.0%"
}, {
    "Type": "tablet",
    "Device": "Amazon Kindle Fire 1st Gen",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "600",
    "HeightPX": "1024",
    "Device-widthPX": "600",
    "Px Per Inch": "169",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "75 : 128",
    "Popularity%": "2.0%"
}, {
    "Type": "phone",
    "Device": "HTC One",
    "Operating System": "Android",
    "Physical Size": "4.7",
    "Physical SizeCM": "12.0",
    "WidthPX": "1080",
    "HeightPX": "1920",
    "Device-widthPX": "360",
    "Px Per Inch": "468",
    "Px Density": "300%  XXHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "1.9%"
}, {
    "Type": "phone",
    "Device": "Droid Razr",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "11.0",
    "WidthPX": "540",
    "HeightPX": "960",
    "Device-widthPX": "360",
    "Px Per Inch": "256",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "1.6%"
}, {
    "Type": "tablet",
    "Device": "BlackBerry PlayBook",
    "Operating System": "BlackBerry",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "1024",
    "HeightPX": "600",
    "Device-widthPX": "1024",
    "Px Per Inch": "169",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "1.6%"
}, {
    "Type": "monitor",
    "Device": "Samsung Chromebook",
    "Operating System": "Chrome",
    "Physical Size": "11.6",
    "Physical SizeCM": "29.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "135",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "1.4%"
}, {
    "Type": "phone",
    "Device": "Droid Razr Maxx",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "11.0",
    "WidthPX": "540",
    "HeightPX": "960",
    "Device-widthPX": "360",
    "Px Per Inch": "256",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "1.4%"
}, {
    "Type": "phone",
    "Device": "Droid 3 & 4",
    "Operating System": "Android",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "540",
    "HeightPX": "960",
    "Device-widthPX": "360",
    "Px Per Inch": "280",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "1.4%"
}, {
    "Type": "phone",
    "Device": "Droid",
    "Operating System": "Android",
    "Physical Size": "3.7",
    "Physical SizeCM": "9.4",
    "WidthPX": "480",
    "HeightPX": "854",
    "Device-widthPX": "320",
    "Px Per Inch": "265",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "1.4%"
}, {
    "Type": "tablet",
    "Device": "Nook Tablet",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "600",
    "HeightPX": "800",
    "Device-widthPX": "600",
    "Px Per Inch": "167",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "3 : 4",
    "Popularity%": "1.3%"
}, {
    "Type": "monitor",
    "Device": "Acer Chromebook",
    "Operating System": "Chrome",
    "Physical Size": "11.6",
    "Physical SizeCM": "29.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "135",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "1.3%"
}, {
    "Type": "phone",
    "Device": "HTC Desire HD",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "11.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "217",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "1.2%"
}, {
    "Type": "tablet",
    "Device": "Asus Transformer",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "1200",
    "HeightPX": "1920",
    "Device-widthPX": "800",
    "Px Per Inch": "224",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "1.2%"
}, {
    "Type": "tablet",
    "Device": "Asus Nexus 7 (2013)",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "1200",
    "HeightPX": "1920",
    "Device-widthPX": "600",
    "Px Per Inch": "323",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "N / A",
    "Popularity%": "1.2%"
}, {
    "Type": "phone",
    "Device": "HTC Desire",
    "Operating System": "Android",
    "Physical Size": "3.7",
    "Physical SizeCM": "9.4",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "252",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "1.1%"
}, {
    "Type": "monitor",
    "Device": "ASUS K55N-DS81 15.6 in",
    "Operating System": "Windows",
    "Physical Size": "15.6",
    "Physical SizeCM": "40.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "100",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "1.1%"
}, {
    "Type": "tablet",
    "Device": "Microsoft Surface Pro",
    "Operating System": "Windows",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "1920",
    "HeightPX": "1080",
    "Device-widthPX": "1280",
    "Px Per Inch": "208",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.7%"
}, {
    "Type": "monitor",
    "Device": "Sony Xperia Z",
    "Operating System": "Android",
    "Physical Size": "5.0",
    "Physical SizeCM": "12.7",
    "WidthPX": "1080",
    "HeightPX": "1920",
    "Device-widthPX": "360",
    "Px Per Inch": "441",
    "Px Density": "300%  XXHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "0.6%"
}, {
    "Type": "tablet",
    "Device": "Microsoft Surface",
    "Operating System": "Windows",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "1366",
    "HeightPX": "768",
    "Device-widthPX": "1366",
    "Px Per Inch": "148",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.6%"
}, {
    "Type": "tablet",
    "Device": "Galaxy Note 10.1",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "800",
    "HeightPX": "1280",
    "Device-widthPX": "800",
    "Px Per Inch": "149",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "5 : 8",
    "Popularity%": "0.6%"
}, {
    "Type": "monitor",
    "Device": "Dell UltraSharp U3011 30\" Monitor",
    "Operating System": "Windows",
    "Physical Size": "30.0",
    "Physical SizeCM": "76.0",
    "WidthPX": "2560",
    "HeightPX": "1600",
    "Device-widthPX": "2560",
    "Px Per Inch": "100",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.6%"
}, {
    "Type": "monitor",
    "Device": "Dell UltraSharp U2711 27\" Monitor",
    "Operating System": "Windows",
    "Physical Size": "27.0",
    "Physical SizeCM": "69.0",
    "WidthPX": "2560",
    "HeightPX": "1440",
    "Device-widthPX": "2560",
    "Px Per Inch": "109",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.6%"
}, {
    "Type": "monitor",
    "Device": "Dell UltraSharp U2412M 24\" Monitor",
    "Operating System": "Windows",
    "Physical Size": "24.0",
    "Physical SizeCM": "61.0",
    "WidthPX": "1920",
    "HeightPX": "1200",
    "Device-widthPX": "1920",
    "Px Per Inch": "94",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.6%"
}, {
    "Type": "phone",
    "Device": "BlackBerry Q10",
    "Operating System": "BlackBerry",
    "Physical Size": "3.1",
    "Physical SizeCM": "7.9",
    "WidthPX": "720",
    "HeightPX": "720",
    "Device-widthPX": "360",
    "Px Per Inch": "330",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "1 : 1",
    "Popularity%": "0.6%"
}, {
    "Type": "phone",
    "Device": "BlackBerry Z10",
    "Operating System": "BlackBerry",
    "Physical Size": "4.2",
    "Physical SizeCM": "10.7",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "384",
    "Px Per Inch": "356",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "0.5%"
}, {
    "Type": "phone",
    "Device": "HTC Evo",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "11.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "217",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "0.4%"
}, {
    "Type": "monitor",
    "Device": "Dell U2713HM 27\" Monitor",
    "Operating System": "Windows",
    "Physical Size": "27.0",
    "Physical SizeCM": "69.0",
    "WidthPX": "2560",
    "HeightPX": "1440",
    "Device-widthPX": "2560",
    "Px Per Inch": "109",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.4%"
}, {
    "Type": "monitor",
    "Device": "Dell S2340M 23\" Monitor",
    "Operating System": "Windows",
    "Physical Size": "23.0",
    "Physical SizeCM": "58.0",
    "WidthPX": "1920",
    "HeightPX": "1080",
    "Device-widthPX": "1920",
    "Px Per Inch": "96",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.4%"
}, {
    "Type": "monitor",
    "Device": "Apple 30\" Cinema Display",
    "Operating System": "OS X",
    "Physical Size": "30.0",
    "Physical SizeCM": "76.0",
    "WidthPX": "2560",
    "HeightPX": "1600",
    "Device-widthPX": "2560",
    "Px Per Inch": "100",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.4%"
}, {
    "Type": "phone",
    "Device": "Alcatel One Touch Ultra 995",
    "Operating System": "Android",
    "Physical Size": "4.3",
    "Physical SizeCM": "10.9",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "217",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "0.3%"
}, {
    "Type": "phone",
    "Device": "Alcatel One Touch Idol Ultra",
    "Operating System": "Android",
    "Physical Size": "4.7",
    "Physical SizeCM": "11.9",
    "WidthPX": "720",
    "HeightPX": "1280",
    "Device-widthPX": "360",
    "Px Per Inch": "316",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "0.3%"
}, {
    "Type": "phone",
    "Device": "Samsung Nexus S",
    "Operating System": "Android",
    "Physical Size": "4.0",
    "Physical SizeCM": "10.0",
    "WidthPX": "480",
    "HeightPX": "800",
    "Device-widthPX": "320",
    "Px Per Inch": "235",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "0.2%"
}, {
    "Type": "tablet",
    "Device": "Motorola Xoom",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "26.0",
    "WidthPX": "1280",
    "HeightPX": "800",
    "Device-widthPX": "853",
    "Px Per Inch": "149",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.2%"
}, {
    "Type": "monitor",
    "Device": "Apple Thunderbolt Display",
    "Operating System": "OS X",
    "Physical Size": "27.0",
    "Physical SizeCM": "69.0",
    "WidthPX": "2560",
    "HeightPX": "1440",
    "Device-widthPX": "2560",
    "Px Per Inch": "109",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.2%"
}, {
    "Type": "tablet",
    "Device": "Ainol Novo 9 Spark",
    "Operating System": "Android",
    "Physical Size": "9.7",
    "Physical SizeCM": "25.0",
    "WidthPX": "2048",
    "HeightPX": "1536",
    "Device-widthPX": "1024",
    "Px Per Inch": "264",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "4 : 3",
    "Popularity%": "0.2%"
}, {
    "Type": "tablet",
    "Device": "Ainol Novo 7 Crystal",
    "Operating System": "Android",
    "Physical Size": "7.0",
    "Physical SizeCM": "18.0",
    "WidthPX": "1024",
    "HeightPX": "600",
    "Device-widthPX": "1024",
    "Px Per Inch": "169",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "16 : 9",
    "Popularity%": "0.2%"
}, {
    "Type": "tablet",
    "Device": "Ainol Novo 10 Hero",
    "Operating System": "Android",
    "Physical Size": "10.0",
    "Physical SizeCM": "25.0",
    "WidthPX": "1280",
    "HeightPX": "800",
    "Device-widthPX": "1280",
    "Px Per Inch": "151",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.2%"
}, {
    "Type": "monitor",
    "Device": "Chromebook Pixel",
    "Operating System": "Chrome",
    "Physical Size": "12.9",
    "Physical SizeCM": "33.0",
    "WidthPX": "2560",
    "HeightPX": "1700",
    "Device-widthPX": "1280",
    "Px Per Inch": "239",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 2",
    "Popularity%": "0.1%"
}, {
    "Type": "tablet",
    "Device": "Toshiba AT100",
    "Operating System": "Android",
    "Physical Size": "10.1",
    "Physical SizeCM": "25.7",
    "WidthPX": "1280",
    "HeightPX": "800",
    "Device-widthPX": "853",
    "Px Per Inch": "149",
    "Px Density": "150%  HDPI",
    "Aspect Ratio": "8 : 5",
    "Popularity%": "0.0%"
}, {
    "Type": "phone",
    "Device": "iPhone 6+",
    "Operating System": "iOS",
    "Physical Size": "5.5",
    "Physical SizeCM": "14.0",
    "WidthPX": "1080",
    "HeightPX": "1920",
    "Device-widthPX": "414",
    "Px Per Inch": "401",
    "Px Density": "N/A  undefined",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "0.0%"
}, {
    "Type": "phone",
    "Device": "iPhone 6",
    "Operating System": "iOS",
    "Physical Size": "4.7",
    "Physical SizeCM": "11.9",
    "WidthPX": "750",
    "HeightPX": "1334",
    "Device-widthPX": "375",
    "Px Per Inch": "326",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "9 : 16",
    "Popularity%": "0.0%"
}, {
    "Type": "tablet",
    "Device": "Apple iPad Mini with Retina",
    "Operating System": "iOS",
    "Physical Size": "7.9",
    "Physical SizeCM": "20.0",
    "WidthPX": "1536",
    "HeightPX": "2048",
    "Device-widthPX": "768",
    "Px Per Inch": "326",
    "Px Density": "200%  XHDPI",
    "Aspect Ratio": "3 : 4",
    "Popularity%": "0.0%"
}, {
    "Type": "tablet",
    "Device": "Acer Picasso",
    "Operating System": "Android",
    "Physical Size": "11.6",
    "Physical SizeCM": "29.0",
    "WidthPX": "768",
    "HeightPX": "1280",
    "Device-widthPX": "768",
    "Px Per Inch": "190",
    "Px Density": "100%  MDPI",
    "Aspect Ratio": "3 : 5",
    "Popularity%": "0.0%"
}]